### ISSUE TITLE
DetailComponent.ByCurve Node

### ISSUE THREAD

**Issue by madeforworship** [andydandy74/ClockworkForDynamo#61] opened 2015-09-01 00:34 UTC
Hey guys, is it possible to update this node to receive a list of Family Types instead of only one?  Right now it appears I can input a list of curves, but only assign one family type to all of them.  I want to be able to assign a 1 to 1.  In this way, I can specify which family type I want, per curve.

Is this possible??  Is it an easy python code change you would share?  I posted the question on DynamoBIM forum here as well:

http://dynamobim.com/forums/topic/drawing-in-revit-lines-details-line-based-families/

Thank you!

**Comment by andydandy74** [comment] 2015-09-07 03:41
This is definitely possible - I'll add it in the next release. For the time being, please use the solution Dimitar provided on the forum.

**Comment by madeforworship** [comment] 2016-02-04 20:21
@andydandy74 I'm having an odd issue, and I apologize for posting it here but it is related to this same node.  See attached screenshot.  I fee like I'm feeding the node everything it is asking for and I've gotten it to work in the past.  Neither the List.Combine or grab the top item from each list is working.  I've tried dynamo .9 and .8.2 (.8.2 is where I was using the script and it was working before).  I've tried updating to the most recent version of clockwork in both versoins and it just doesn't work.  I've confirmed that the elevation of the line I'm feeding it is the same elevation of the view, 100'.

![image](https://cloud.githubusercontent.com/assets/10763679/12828427/5c016392-cb4a-11e5-9275-d1e16401bd44.png)

Not sure if the error message on the node means anything to you.  Please let me know!

**Comment by madeforworship** [comment] 2016-02-04 21:13
Ok so after a little testing, it errors out when I pass it an "Area Plan" type of view.  Floor Plan view seems to work.  Wierd thing is this script used to work when I passed it an area plan view...any ideas?

**Comment by andydandy74** [comment] 2016-02-04 21:21
@madeforworship - I wonder if this is perhaps caused by the data type set for the ```view``` input. Can you please try the following and report back if it solved the issue: In the custom node remove the data type for the ```view``` input: " : View"
![capture](https://cloud.githubusercontent.com/assets/3014437/12830029/74b54118-cb8d-11e5-86f0-7986b311fa0f.PNG)

**Comment by madeforworship** [comment] 2016-02-04 22:09
Hallelujah! That worked!  I was racking my brain over this one!  Thanks so much Andreas

**Comment by andydandy74** [comment] 2016-02-05 06:55
Great. I'll make sure to edit this in for the next release and will file an issue with the Dynamo team.

**Comment by andydandy74** [comment] 2016-11-28 05:48
I am going to close this as there is now a built-in node to make detail curves.

**Closed by andydandy74** 2016-11-28 05:48 UTC
Labels: Dependency, Improvement
