### ISSUE TITLE
Revit 2019 and Dynamo 2.x Crashes when clockwork is loaded. Mostly with other packages.

### ISSUE THREAD

**Issue by Freddeket** [andydandy74/ClockworkForDynamo#236] opened 2018-11-27 09:37 UTC
**Describe the bug**
When I create a dynamo script with Clockwork elements combined with other packages I get a full crash (Revit and Dynamo)

**Steps to Reproduce**
Uninstall all packages. Reinstall packages after opening script. Then it works. 

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: Windows 
- Dynamo version: 2.0.1
- Clockwork version: 2.x
- Revit version: 2019.1

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [v ] I am running a *supported* Clockwork version
- [v] I am running the *latest available* Clockwork version
- [v] My installed version of Clockwork matches the Dynamo version it's installed for
- [v] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [v ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by Freddeket** [comment] 2018-11-27 09:40
https://forum.dynamobim.com/t/archi-lab-and-dynamo-2-0-1/23120
Similar Issue

**Comment by Freddeket** [comment] 2018-11-27 09:48
I think I know where the problem is: I have created custom nodes with clockwork dependencies.  Maybe that bugs? Shall I remove the clockwork nodes and replace them by the python code in them?

**Comment by andydandy74** [comment] 2018-11-29 20:01
Let's see if this fixes it:
https://github.com/DynamoDS/Dynamo/pull/9253

**Comment by andydandy74** [comment] 2019-08-15 04:59
I believe the cause for this was fixed in either Dynamo 2.0.2 or 2.0.3

**Closed by andydandy74** 2019-08-15 04:59 UTC
Labels: Bug, Dependency
